### PR TITLE
fix complie error with msvc

### PR DESCRIPTION
**Pull request by luoyetx**

### CODE REVIEW

**Comment by vog** [comment]
I'd like to keep this open, as fixing the compiler error is still an important thing to do. (I just think this should be solved in a different way.)

**Comment by vog** [comment]
@luoyetx Thanks again for bringing this issue up. I finally cleaned up this code, and fixed the dynamic buffer issue on that way.

Would you mind checking that the latest version (a5d3717fe7df383fc50204ea7c8f5e5943fa1f11) compiles on your system without any error?

**Comment by luoyetx** [comment]
@vog the latest version is fine with msvc12, no error :smile:

**Comment by vog** [comment]
Wow, you're quick! Thanks. So we can close this issue.

**Comment by vog** [comment]
I just release a new version 1.2 that contains all improvements.

https://github.com/vog/sha1/releases/tag/1.2

**Comment by luoyetx** [comment]
Thanks

**Pull request closed without merging**
