### PR TITLE
Header-only library

### PR DESCRIPTION
**Pull request by zlatko-michailov**
Fixes vog/sha1/#5.

Make it a header-only library.
- Continue including sha1.hpp as before.
- It is no longer required to compile and link sha1.cpp. However, projects that already compile and link sha1.cpp will not be broken.

### CODE REVIEW

**Comment by vog** [comment]
Thanks for your contribution! Here's my feedback from a quick review:

1. Please feel free to add your personal website to README.org, not just your name.
1. Please provide the .gitignore in a separate pull request (and remove the empty line inside .gitignore)
1. What is the point of of `sha1.i.hpp`? It is only ever included by `sha1.hpp`, so why not putting its contents in right there? After all, part of the charm of a header-only library is that it is actually just a single file, not 2 files.
1. Why does `sha1.cpp` include `sha1.hpp`? Isn't that a waste of compilation time? Can't we just leave it empty, perhaps with a comment explaining that it has been left empty for backwards compatibility?
1. What is the point of `test_dummy.cpp`? It seems that it is only used to test multiple inclusions of `sha1.hpp`. In that case, can't we just double-include `sha1.hpp` into `test_sha1.cpp`, remove `test_dummy.cpp` and revert the rest of `test_sha1.cpp`?

**Comment by zlatko-michailov** [comment]
Thanks for the feedback! All points make sense. I'll address them shortly.

**Comment by zlatko-michailov** [comment]
Regarding 5. above, there is a difference between including a header twice from the same source file and linking two different .cpp files that include the same header. The former is tests the macro in the header file (although I like `#pragma once` better) while the latter tests the `inline`'s. I care about the latter. (I am confident the former is solid.)

I agree to remove `test_dummy.cpp`. Then, I will also remove the second `#include "sha1.hpp"`, which should effectively put `test_sha1.cpp` exactly where it was.

**Comment by vog** [comment]
Thanks! We're getting close. Result of the second review:

1. `sha1.cpp` contains a stray empty line at the end. Moreover, the comment should be shortened to the first 3 lines - the rest is redundant with the initial comment of `sha1.hpp`.
1. To keep double-link test, we could just link `sha1.hpp` in addition to `test_sha1.cpp` into the `test_sha1` executable. What do you think?
1. We were using `#ifndef` instead of `#pragma once`, because `#pragma once` is not standardized. In case this changed meantime, feel free to challenge this in a separate pull request.
1. Please include `sha1.hpp` twice in `test_sha1.cpp`.
1. Please order all `#include`s alphabetically, to improve readability.
1. Please provide your `.gitignore` as a separate pull request, and remove the empty line in the middle.

**Comment by zlatko-michailov** [comment]
Thank you for your patience! I am also excited that we are making progress. Here are my responses point-by-point, before I make the changes:
1. Will do.
2. What you are proposing will not test the `inline`s. You may give the compiler a ton of definitions, but until you start calling them, it will not generate code for them, e.g. it doesn't generate code for all the `std` headers you include - only for definitions that you actually use. That's why I had added another, dummy, .cpp file that was using the definitions from the header. I can't think of an approach where we could link the same meaningful file twice, because there will be a duplicate definition. We have to split the tests into two .cpp files. Perhaps take slow into a separate .cpp file? I am open to suggestions.
3. Will do this. It won't verify emptiness, but it will verify backcompat. So I agree we should do it.
4. No op. I don't insist on `#pragma once`.
5. Will do. I just want to be sure you realize this doesn't test anything beyond the macro.
6. Will do. I did it temporarily, and when I saw that `<ostream>` had ended up (several notches) after `<fstream>`, I found it confusing. Anyway, I don't have a strong opinion on this. I'll go with your choice.
7. I haven't forgotten it. Will do that after this PR is merged, as you requested.

If you are OK with everything except 2., please confirm. I can prepare another iteration. You can think more about 2. meanwhile.

**Comment by vog** [comment]
I agree with your proposals. Some details:

Regarding 2, I now understand why we need a separate `.cpp` file to test this properly. I like your idea of splitting slow and fast tests into separate files.

Regarding 6, I indeed prefer lexical order over topological order, as it is easier to maintain and not ambiguous.

Regarding 7, I just wanted to make you aware that the modified .gitignore is still in the changeset of this pull request.

**Comment by zlatko-michailov** [comment]
Re 7: GitHub's diffing capabilities are no good. To review the change, please clone [my fork](https://github.com/zlatko-michailov/sha1.git) to a temp folder, and:
- Verify the 3 commits on top of your `HEAD` are indeed the 3 commits in this PR.
- Use your favorite tool to diff `HEAD~3..HEAD`.
- If you have any doubts about the .gitignore file, do `git show --name-status HEAD~1` to verify the file was removed in that commit.

If I've missed something, please let me know. It hasn't been intentional.

**Comment by vog** [comment]
Regarding the .gitignore: Sorry, my bad. GitHub is showing it correctly. I have idea what went wrong on my side.

Now it's almost perfect. My review now contains only nitpicks:

* I like your idea to immitate "sha1sum" in the extra file, rather than moving the slow tests to it. However, then the file name should be changed to `test_sha1_file.cpp` or `test_file.cpp`.
* The second line of the extra cpp file doesn't match its filename.
* The extra cpp file should have an explaining comment about why it is not part of sha1 (i.e. the link test)
* Also, another short comment should be at the "extern" line in `test_sha1.cpp`, at least to explain from which file the function will be taken, perhaps also mentioning the link test.

**Comment by zlatko-michailov** [comment]
Ping?

**Comment by zlatko-michailov** [comment]
Thanks!

**Comment by vog** [comment]
The final review was successful. Thanks a lot for your contribution!

**Pull request merged**
